### ISSUE TITLE
Usee ?

### ISSUE THREAD

**Issue by sucks05** [mwafa/iptv-id#1]
yang usee belum work ya bro ?
cara load nya gimana ya ? saya coba http://localhost:3000/usee?id=net kok ga bisa ya..

**Comment by mwafa** [comment]
Untuk usee dia spesial 

Jadi langsung

http://localhost:3000/usee/net

**Comment by sucks05** [comment]
> Untuk usee dia spesial
> 
> Jadi langsung
> 
> http://localhost:3000/usee/net

siap bro.. bisa tapi bukan pake vlc heheh, saya coba pake smartiptv (chrome extension) ketika di load muncul pilihan resolusinya, 180P, 360P dst. harus di click dulu baru ter play

**Comment by sucks05** [comment]
![usee](https://user-images.githubusercontent.com/87424225/128217427-28b3a1c4-6f82-40b1-a4fa-fa0cbdbc8c0f.png)
