### ISSUE TITLE
No hostname/IP on self-hosted

### ISSUE THREAD

**Issue by ardhipoetra** [mwafa/iptv-id#2]
After do `npm install` and `npm run`, `http://localhost:3000/playlist.m3u` indeed can be accessed. 

However, the playlist misses the hostname/IP address (or even `localhost`) such as : 
```
.....
#EXTINF:-1 tvg-logo="https://mytuner.global.ssl.fastly.net/media/radios-150px/ANm8fKJ5nb.png" group-title="radio", HARD ROCK
/vidio?id=7053&token=true

#EXTINF:-1 tvg-logo="https://mytuner.global.ssl.fastly.net/media/radios-150px/t4lc5jhzvcry.png" group-title="radio", BAHANA FM
/vidio?id=7091&token=true

#EXTINF:-1 tvg-logo="https://mytuner.global.ssl.fastly.net/media/radios-150px/chpcnjxyuchl.png" group-title="radio", GERONIMO FM
/vidio?id=7216&token=true
```

Kalau ada parameter atau konfigurasi mau di-bind ke IP yang mana that would be so much better.

**Comment by mwafa** [comment]
You can try this command bellow

```
npm start --port 3000 --domain http://localhost:3000
```

---
Refer on https://github.com/mwafa/iptv-id/commit/45cddf825d3c5ae149f17d0e3585fa8cb66ee86b
